### PR TITLE
Create data set on overall vaccination rates

### PR DESCRIPTION
**Pull request by rafagarciac**
Add new overall_vaccination_twelve_to_twenty_three_months.csv file.

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
@rafagarciac 

Thank you for submitting the PR. Can you please take a look at the following issues?

1. It looks like the only value here is "BASIC". Why are there no rows for "NONE" or "ALL"? Are 100% of the children in each province in the "All basic vaccinations" column?
2. Small thing, but there should be a space between the word Province and the number, so, for example, "Province 1" instead of "Province1"

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

do you plan on updating your PR or should we open up the issue for someone else to complete?

**Comment by cliftonmcintosh** [comment]
Closing because the data are incorrect and @rafagarciac has not responded to inquires about whether they will be corrected.

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

My apologies. I realize now you may have been waiting for guidance about the percentages. I have updated the description in #37 

If you would like to update this PR based on that guidance, please let me know.

**Comment by cliftonmcintosh** [comment]
Re-opening for @rafagarciac to address change request

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

Thank you for the update.

I have done some spot-checking. "BASIC" and "ALL" seem to be reversed for Province 1 but not for Province 2. I have not gone through all of the provinces. Can you please double-check?

**Comment by rafagarciac** [comment]
Ok, yes I had a mistake because it was the first one. However I reviewed all Provinces and it's seems that all operations are correct ! ✔️ b287a07ebb1a655084328cc4382c845111a4296c

**Review by cliftonmcintosh — APPROVED** [review]

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

Thank you for your contribution.

**Pull request merged**
