### PR TITLE
Pneumococcal vaccination rates

### PR DESCRIPTION
**Pull request by Gage77**

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
@Gage77 

Thank you for submitting the PR. Right now it has 783 files changed, though. Can you please correct the PR so that it only has the one relevant file changed?

**Comment by cliftonmcintosh** [comment]
@Gage77 

do you plan on updating this PR or should we open up the issue for someone else to complete?

**Comment by Gage77** [comment]
My sincerest apologies. Please open up this PR for someone else to complete. Had some things come up and I won't be able to complete it at this time.
Best of luck with this project!

**Comment by cliftonmcintosh** [comment]
Closing because this PR has hundreds of extra files in it.

**Pull request closed without merging**
