### PR TITLE
Adds data file for polio vaccinations [#32]

### PR DESCRIPTION
**Pull request by msdeibel**

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
@msdeibel 

Thank you for the contribution. I have two small change requests, please.
1. Can you please check the rounding on the percentages? The numbers don't all add up to the total on all the provinces. Please feel free to choose a rounding strategy that seems sensible and gets the same number of children as is in the original data set
- Province 1 in this file all adds up to 168 but the data says there were 169.
- Province 3 in this file all adds up to 167 but the data says there were 168.
- Province 6 in this file all adds up to 64 but the data says there were 63.
- Province 7 in this file all adds up to 83 but the data says there were 84.
2. Can you please include the word "Province" in the province column for each row? For example, "Province 1" instead of just "1". That will allow us to have a common standard for the files in this data set.

Thank you.

**Comment by msdeibel** [comment]
I'll fix that tonight.

**Comment by msdeibel** [comment]
The fix is in. Please check the rounding strategy in the commit messsage.

**Review by cliftonmcintosh — APPROVED** [review]
Thank you, @msdeibel

**Pull request merged**
