### PR TITLE
Normalize CSV by removing first row above headers

### PR DESCRIPTION
**Pull request by cliftonmcintosh**
This normalizes the agriculture CSVs so that the header row is the first row. This should make it easier to process the data (and, FWIW, also easier for it to be displayed in a pretty format in GitHub).

### CODE REVIEW

**Comment by nikeshbalami** [comment]
Ohh I will keep this in mind while pushing others datasets @cliftonmcintosh Thanks for removing it from previous datasets 👍

**Comment by cliftonmcintosh** [comment]
@amitness 

Would you review this pull request? I don't want to self-merge.

**Review by amitness — CHANGES_REQUESTED** [review]
Please check Line 26 here: https://github.com/cliftonmcintosh/data/blob/5c60fe32731b986b0bcd39b40ad69b072796f37d/datasets/agriculture/coffee.csv#L26

**Comment by cliftonmcintosh** [comment]
@amitness

That is an existing issue with the data. I am not sure how it should be dealt with. If that is what is in the PDF, this data will need extra work if we want to put it in NepalMap.

**Comment by amitness** [comment]
@cliftonmcintosh I checked the PDF [here](http://moad.gov.np/public/uploads/1142453195-STATISTIC%20AGRICULTURE%20BOOK_2016.pdf) and it should be "Other 17 Districts" instead of "25 Other 17 Districts"

**Comment by amitness** [comment]
@cliftonmcintosh Yes, seems not all districts are included in coffee data.

**Comment by nikeshbalami** [comment]
Yes since the products like Tea, Coffee, Honey, Jute, Cotten are grown in certain part of the country, not all districts are included in data.

**Comment by cliftonmcintosh** [comment]
@amitness Updated incorrect coffee row

**Review by amitness — APPROVED** [review]

**Pull request merged**
