### PR TITLE
Create pentavalent_vaccination_twelve_to_twenty_three_months.csv

### PR DESCRIPTION
**Pull request by SarahLizDettloff**
Response to Create data set on DPT-HepB-Hib (pentavalent) vaccination rates among children ages 12-23 months #33

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
These data are incorrect. For example, these data list 169 children between the ages of 12-23 months having received no prevalent vaccinations in Province 1. That would mean none of the children in that age group received any doses of the vaccine. That does not fit what is in the data.

Please see the guidance in https://github.com/Code4Nepal/data/issues/33.

**Comment by SarahLizDettloff** [comment]
@cliftonmcintosh, Thank you for your feedback! I have made the requested change.

**Comment by cliftonmcintosh** [comment]
@SarahLizDettloff 

Thank you for the update. The multi-dose statistics require a little explaining in order for the numbers to be calculated.

The statistics for 1 dose include all the children who had two doses or three doses. That means in order to get the number of children who had **only** one dose, the percentage that had two doses needs to be subtracted from the one dose percentage. For example, in Province 1, there are 93.5% of the children reported as receiving one dose, 92.4% reported as receiving two doses, and 85.6% as receiving three doses. This means 1.1% of the children received **only** one dose, 6.8% of the children received **only** two doses, 85.6% of the children received all three doses, and 6.5% (100% - the number who received at least one dose) received no vaccine at all.

I believe when you first took on this story, the description did not include that explanation. I added it afterwards. My apologies for the miscommunication.

Would you be able to re-submit? We would love to have the data available.

**Comment by SarahLizDettloff** [comment]
@cliftonmcintosh thank you for explaining that. I have resubmitted it. Please let me know if you would like any additional changes.

**Comment by cliftonmcintosh** [comment]
@SarahLizDettloff 

thank you for the update. The percentages look correct. However, can you now use them to create raw numbers? For example, in province 1, if 1.1% of the children received one dose, then the "total" would be 169 * 0.011, rounded  to "2".

The number we need is the percentage times the total number of children ages 12-23 in the survey in each province.

Please let me know if you have any questions. And, again, thank you for contributing.

**Comment by SarahLizDettloff** [comment]
@cliftonmcintosh , thank you for pointing that out. I should of asked for clarity. I have updated the PR.

**Comment by cliftonmcintosh** [comment]
@SarahLizDettloff 

The "total" field should be a whole number that is the total number of children for a province divided by the percentage of them that has received a certain number of pentavalent doses. For example, in province 1, if 1.1% of the children received one dose, then the "total" would be 169 * 0.011, rounded to "2".

**Comment by SarahLizDettloff** [comment]
Got it. I have updated it, and verified the totals. Please let me know if there is anything else. Thank you for your feedback!

**Review by cliftonmcintosh — APPROVED** [review]

**Comment by cliftonmcintosh** [comment]
Looks good. Thank you, @SarahLizDettloff !

**Pull request merged**
